{{- include "kubeslice.validateImageConfig" . -}}
{{- if include "kubeslice.createImagePullSecret" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.imagePullSecrets.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubeslice-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: image-pull-secret
  annotations:
    {{- include "kubeslice.imagePullAnnotations" . | nindent 4 }}
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "kubeslice.dockerconfigjson" . }}
{{- end }}
