{{- include "kubeslice.validateImageConfig" . -}}
{{- if include "kubeslice.createImagePullSecret" . }}
---
# Secret in release namespace (kubeslice-system)
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.imagePullSecrets.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubeslice-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: image-pull-secret
  annotations:
    {{- include "kubeslice.imagePullAnnotations" . | nindent 4 }}
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-20"
    "helm.sh/hook-delete-policy": before-hook-creation
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "kubeslice.dockerconfigjson" . }}
---
# Secret in spire namespace (required for SPIRE components)
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.imagePullSecrets.secretName }}
  namespace: spire
  labels:
    {{- include "kubeslice-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: image-pull-secret
  annotations:
    {{- include "kubeslice.imagePullAnnotations" . | nindent 4 }}
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-20"
    "helm.sh/hook-delete-policy": before-hook-creation
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "kubeslice.dockerconfigjson" . }}
---
# Secret in kubeslice-nsm-webhook-system namespace (required for NSM admission webhook)
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.imagePullSecrets.secretName }}
  namespace: kubeslice-nsm-webhook-system
  labels:
    {{- include "kubeslice-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: image-pull-secret
  annotations:
    {{- include "kubeslice.imagePullAnnotations" . | nindent 4 }}
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-20"
    "helm.sh/hook-delete-policy": before-hook-creation
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "kubeslice.dockerconfigjson" . }}
{{- end }}
